language: java

jdk:
  - oraclejdk8
 
services:
  - redis-server
  - rabbitmq
  
before_script:
  # install NATS server
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.1.0/gnatsd-v1.1.0-linux-amd64.zip -qO gnatsd.zip
  - unzip gnatsd.zip
  - ./gnatsd-v1.1.0-linux-amd64/gnatsd &
  
install: gradle wrapper --gradle-version 4.2
  
before_install:
  - chmod +x gradlew
  
script: ./gradlew check
